### PR TITLE
Fixed styling on discovering stories

### PR DESCRIPTION
**Pull request by sthewissen**
Still has some problems:

- Shadow is missing, but shadow is REALLY crappy cross platform. `Frame` has a `HasShadow` property but you can't style the shadow to look the same across platforms. Especially Droid is very stubborn here.
- Image should probably be replaced by CachedImage in FFImageLoading, but not sure if that's something you want to include.

### CODE REVIEW

**Comment by sthewissen** [comment]
Case in point regarding the shadow... Also due to a layering issue in `Frame` the Image is rendered OVER the `Frame`'s rounded corners instead of being contained within them. I've developed a RoundedContentView supporting basic shadow, rounded corners and gradient backgrounds for exactly this purpose. Will look into adding that in here instead if you want.

screenshot 2019-01-11 at 16 00 50

**Comment by Depechie** [comment]
@sthewissen thanks for the PR!
Will merge this as it's a great starting point for the current design.
Would like to handle 2 things after this ( will also put them up as issues ).
1. Indeed try to have rounded corner images
2. Maybe we can 'fake' shadow instead of actually using the Frame control ( need to think about other options )

**Comment by sthewissen** [comment]
1. I think a frame like control that clips its content correctly could also work and be usable across the app.
2. Thing is, in iOS we can go pretty far with shadows. Color, blur size, positioning etc. However, on Droid we only have the Elevation to play around with. This means if we would go for a custom control like in (1) we COULD pull of the shadows as designed on iOS and tone it down on Droid. Would involve a custom renderer though.

**Comment by Depechie** [comment]
Thinking out loud here, but in the 'old' windows phone days ( when we did not yet have all the fancy UI controls ), we faked this by drawing a blurred/opacity adjusted rectangle and positioning it underneath the image ( or other UI ).
Looked great and was easy to implement. If this can be done in Xamarin Forms, this would also benefit the same look and feel across iOS and Android.
But have not yet tried this on XF.

**Pull request merged**
